# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 956160c7a923ab0c15e56d765722c55c5796f3277afddfd3bd4c9abef160f8535585eaac111f2aba7c3f5f24f025a3d6465837fbfe570b4e665d8cb1e9614f0b

test:
  secret_key_base: 0a2ab57b051391e042cadfd3e82cd3403f21c682a9bcc695f4b86f6f24a69b6951fa87c494ce6371f46d6ed514930e6b9e1e10a0e67ae92750eb989672ac3501

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
